export const FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID;
export const FIREBASE_DATABASE_URL =
  process.env.REACT_APP_FIREBASE_DATABASE_URL;
export const FIREBASE_KEY = process.env.REACT_APP_FIREBASE_KEY;
export const FIREBASE_STORAGE_URL = process.env.REACT_APP_FIREBASE_STORAGE_URL;
export const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
